name: edu_ebook
description: Live by Quran is app about Quran ebooks
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.19.0
  flutter_bloc: ^5.0.0
  equatable: ^1.2.5
  cached_network_image: ^2.3.3
  dartz: ^0.9.2
  provider: ^4.0.1
  permission_handler: ^4.2.0+hotfix.1
  get_it: ^4.0.2
  package_info: ^0.4.0+2
  shared_preferences: ^0.5.12+4
  hive: ^1.4.4+1
  flutter_staggered_grid_view: ^0.3.2
  esys_flutter_share: ^1.0.2
  bloc: ^5.0.0
  objectdb: ^1.0.7+1
  flutter_rating_bar: ^3.2.0+1
  epub_viewer: ^0.1.9
  path_provider: ^1.6.24
  uuid: ^2.2.0
  progress_dialog: ^1.2.2
  delayed_display: ^1.1.0
  dio: ^3.0.9
  flutter_pdfview: ^1.0.4
  bottom_navy_bar: ^5.6.0
  url_launcher: ^5.5.1
  typicons_flutter: ^0.4.2
  carousel_slider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/flags/
    - assets/images/
    - assets/logos/
    - lib/language/ar.json
    - lib/language/en.json

  fonts:
    - family: Alarabiya
      fonts:
        - asset: fonts/al-alarabiya.ttf
        #  style: italic
    - family: Insan
      fonts:
        - asset: fonts/insan.ttf
        #  style: italic
